---

- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
       name: my-app
       api_version: v1
       kind: Namespace
       state: present
       kubeconfig: /root/.kube/config
    - name: Deploy nginx app
      k8s:
        src: /home/tilemachos/devops-courses/ansible/nginx-config.yaml
        state: present
        kubeconfig: /root/.kube/config
        namespace: my-app
